### ISSUE TITLE
perf-tools: investigate intermittent crash

### ISSUE THREAD

**Issue by gireeshpunathil** [eclipse-openj9/openj9-utils#30]
@mpirvu reports that the tool faces occasional crashes. (upon pressing ctrl+c on a running process with the tool?)

reproduce it, investigate and fix the root cause.

**Comment by mpirvu** [comment]
Crashes have become much more frequently recently. If I stop the JVM with "ctrl-C' while the collection is in progress I get a crash every single time.
The stack trace is:
```
#12 <signal handler called>
#13 0x00007f7a1ceb9fa1 in Server::handleMessagingClients(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
   from /home/mpirvu/CANOSP/openj9-utils/perf-tool/build/libagent.so
#14 0x00007f7a1ce78e8f in sendToServer(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer, std::vector<unsigned char, std::allocator<unsigned char> > > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) ()
   from /home/mpirvu/CANOSP/openj9-utils/perf-tool/build/libagent.so
#15 0x00007f7a1cea4a48 in MonitorContendedEnter(_jvmtiEnv*, JNIEnv_*, _jobject*, _jobject*) () from /home/mpirvu/CANOSP/openj9-utils/perf-tool/build/libagent.so
#16 0x00007f7a3bdec079 in jvmtiHookMonitorContendedEnter () from /home/mpirvu/sdks/OpenJDK11U-jdk_x64_linux_openj9_11.0.10_9_openj9-0.24.0/lib/compressedrefs/libj9jvmti29.so
#17 0x00007f7a3ea1b3be in J9HookDispatch () from /home/mpirvu/sdks/OpenJDK11U-jdk_x64_linux_openj9_11.0.10_9_openj9-0.24.0/lib/compressedrefs/libj9hookable29.so
#18 0x00007f7a3f125293 in objectMonitorEnterBlocking () from /home/mpirvu/sdks/OpenJDK11U-jdk_x64_linux_openj9_11.0.10_9_openj9-0.24.0/lib/compressedrefs/libj9vm29.so
#19 0x00007f7a3d39215a in old_slow_jitMonitorEntry () from /home/mpirvu/sdks/OpenJDK11U-jdk_x64_linux_openj9_11.0.10_9_openj9-0.24.0/lib/compressedrefs/libj9jit29.so
#20 0x00007f7a3d3a6f2f in jitMonitorEntry () from /home/mpirvu/sdks/OpenJDK11U-jdk_x64_linux_openj9_11.0.10_9_openj9-0.24.0/lib/compressedrefs/libj9jit29.so
```
